"""empty message

Revision ID: bca247fda350
Revises: 
Create Date: 2020-09-09 22:43:40.329780

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'bca247fda350'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transacao',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('estabelecimento', sa.String(length=255), nullable=False),
                    sa.Column('cliente', sa.String(length=255), nullable=False),
                    sa.Column('valor', sa.Integer(), nullable=False),
                    sa.Column('descricao', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transacao')
    # ### end Alembic commands ###
